services:
  app:
    container_name: pomodoro-app
    build: 
      dockerfile: ./infrastructure/Dockerfile.app
      context: .
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000

  web:
    container_name: pomodoro-web
    build: 
      dockerfile: ./infrastructure/Dockerfile.web
      context: .
    volumes:
      - ./:/var/www
      - ./infrastructure/web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  dba:
    container_name: pomodoro-dba
    build: 
     dockerfile: ./infrastructure/Dockerfile.dba
     context: .
    volumes:
      - ./infrastructure/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
